### ISSUE TITLE
 error: 'PageBuilder' has not been declared

### ISSUE THREAD

**Issue by RudyFiero** [Hieromon/PageBuilder#11]
I was trying to use Autoconnect but I was getting the above error. So I tried to compile a PageBuilder example, and I am getting the same error. 

I am using the 2.5.2 release version of ESP8266-Arduino, and Arduino 1.8.9.  Could you tell me what I can do to get this to compile?

```
In file included from C:\Users\Rudy\Documents\Arduino\libraries\PageBuilder\src/PageBuilder.h:21:0,

                 from C:\Users\Rudy\Documents\Arduino\libraries\PageBuilder\examples\WebPageHello\WebPageHello.ino:8:

C:\Users\Rudy\Documents\Arduino\libraries\PageBuilder\src/PageBuilder.cpp:52:6: error: 'PageBuilder' has not been declared

 bool PageBuilder::canHandle(HTTPMethod requestMethod, String requestUri) {

      ^

C:\Users\Rudy\Documents\Arduino\libraries\PageBuilder\src/PageBuilder.cpp: In function 'bool canHandle(HTTPMethod, String)':

C:\Users\Rudy\Documents\Arduino\libraries\PageBuilder\src/PageBuilder.cpp:53:9: error: '_canHandle' was not declared in this scope

     if (_canHandle) {

         ^

C:\Users\Rudy\Documents\Arduino\libraries\PageBuilder\src/PageBuilder.cpp:57:13: error: '_method' was not declared in this scope

         if (_method != HTTP_ANY && _method != requestMethod)

             ^

```

**Comment by Hieromon** [comment]
Attempt to deleting the ~\Documents\Arduino\libraries\PageBuilder folder along with the contents and then reinstalling it using Arduino IDE's Library Manager.
In fact, I think the compiler is reporting errors in addition to the logs you provide.  I recommend tracing the compilation log carefully. This type of error may indicate that your compilation environment is in an incorrect state.

**Comment by RudyFiero** [comment]
I deleted the directories and then reinstalled. They worked after that. 

Thanks for the help.

**Comment by Hieromon** [comment]
That's good to know.
