### ISSUE TITLE
Async Web Server

### ISSUE THREAD

**Issue by mellowmonk** [Hieromon/PageBuilder#12]
Not sure if this qualifies as an issue.

In the past I have used ESPAsyncWebServer for running web pages stored on the esp32 memory.
https://github.com/me-no-dev/ESPAsyncWebServer.git 

Could we run web pages stored on the esp32 memory in a similar way with PageBuilder?

For example, 
For a sketch which also uses AutoConnect, could we call a html page, "example.html" which is stored in the SPIFFS?

**Comment by Hieromon** [comment]
We can make it come to realize.
The current PageBuilder does not conform to ESPAsyncWebServer's RequestHandler, so we need to create a new PageBuilder with AsyncCallbackWebHandler as the base class. And I have finished that implementation.

I implemented it for asynchronous AutoConnect using ESPAsyncWebServer. Asynchronous AutoConnect development is going well, but it still takes time. It works already on the ESP8266 but has some problems with ESP32. The AutoConnectAux implementation is not yet complete.

**Comment by mellowmonk** [comment]
Thanks for the update. Will try to get the pages incorporated in the in Autoconenct library.  
Thank you for you hard work and all the luck for enhancing the functionalities.

**Comment by Hieromon** [comment]
@mellowmonk 
I posted the PageBuilder for ESPAsyncWebServer to [Gist](https://gist.github.com/Hieromon/a93409c62c044515f10f4415c939e6e9).
There are two files, PageBuilder.h and PageBuilder.cpp. It is still under development and will contain bugs. It's also not backward compatibility with the old PageBuilder for the legacy WebServer/ESP8266WebServer, but you can try it if it's worth it to you.
