### ISSUE TITLE
SetUri not working

### ISSUE THREAD

**Issue by anctsys** [Hieromon/PageBuilder#13]
Hi

Thank you for this great library.
I work on ESP8266 (D1 mini)
setUri not working with 
String uri = "/mytest";
uri.c_str() 
or 
String uri = "/mytest";
char uri_buf[uri.length()+1];
uri.toCharArray(uri_buf, uri.length()+1);

The server not redirect to /mytest (error 404)

`
      page.setUri(uri.c_str());
      elm.setMold(PSTR(
        "<html>"
        "<body>"
        "<h2>{{ROOT}}</h2>"
        "</body>"
        "</html>"));
      elm.addToken("ROOT", rootPage);`

But when I using TEST_PAGE.setUri("/mytest"); the sketch work properly.

Best regards

**Comment by anctsys** [comment]
I using ESP8266 (D1 mini)

**Comment by Hieromon** [comment]
PageBulder does not hold an instance of a page URI. A phenomenon similar to your experience will occur if the uri instance does not exist when the page accessed.
For example, if **String uri** is a local variable in some function of the sketch, an instance of the uri is lost at exiting from the function.
This structure of PageBulder is undesirable, so  I will need to improve it.

**Comment by Hieromon** [comment]
Fixed. https://github.com/Hieromon/PageBuilder/commit/62b2ecef443b18315d1263102b21fc07ccd48efe

**Comment by anctsys** [comment]
Thank you
Do you plan this evolution in your development.
