### ISSUE TITLE
Callback runs twice

### ISSUE THREAD

**Issue by orangeskullstudio** [Hieromon/PageBuilder#14]
In the example called FSPage, the callback listSSID runs twice when the page is requested.

**Comment by Hieromon** [comment]
Isn't the client browser sending multiple HTTP GETs to detect a captive portal?
Did you trace and validate the HTTP request?

**Comment by orangeskullstudio** [comment]
I did it. Attached is the Wireshark result between the HTTP GET and the response.

Only one HTTP GET appears. I tried it with the phone, web browser and wget, all with the same result. It makes two calls of just over 2100 ms each.

[result.txt](https://github.com/Hieromon/PageBuilder/files/3981272/result.txt)

**Comment by Hieromon** [comment]
@orangeskullstudio I reproduced the issue. It is a bug since v1.3.3.
Thank you for your report.
