### ISSUE TITLE
Is PageBuilder compatible to run with ESPAsyncWebServer ?

### ISSUE THREAD

**Issue by anctsys** [Hieromon/PageBuilder#16]
Hi
I want using  ESPAsyncWebServer with PageBuilder.
Is it possible to use your library with https://github.com/me-no-dev/ESPAsyncWebServer ?

Thanks

**Comment by Hieromon** [comment]
No, but I posted the prototype of the next enhanced PageBuilder. It will be released along with AutoConnect asynchronous support.
https://github.com/Hieromon/PageBuilder/issues/12#issuecomment-557875293

**Comment by anctsys** [comment]
OK i will test this new feature
