### ISSUE TITLE
add LITTLEFS for esp32

### ISSUE THREAD

**Issue by Eddddddddy** [Hieromon/PageBuilder#23]
I found that I can use littlefs with esp8266, not support for esp32, but my project already use littlefs with esp32. 

so, is there any suggest for me that I can use pagebuilder, littlefs and esp32 together. thanks so much.

**Comment by Hieromon** [comment]
I staged the LITTLEFS support to the [enhance/littlefs](https://github.com/Hieromon/PageBuilder/tree/enhance/littlefs) branch. It has tested on Arduino core 1.0.5 with ESP-IDF v3.3.
I haven't tested it on the idf-4.2 based Arduino core with [LittleFS_esp32](https://github.com/lorol/LITTLEFS) merged.
This enhancement will be merged into PageBuilder v1.5.0.

**Comment by Eddddddddy** [comment]
Thanks for that. I got it. 
waiting for your 1.5.0. fascinating
