### ISSUE TITLE
Add File Pictures ...

### ISSUE THREAD

**Issue by medic00** [Hieromon/PageBuilder#24]
HTTP code <img src="dev1.jpg"/>.
How add this pic from SPIFFS?

**Comment by Hieromon** [comment]
The only context MIME that PageBuilder responds to is `text/html`. The content for `image/jpeg` is not supported. You can respond to jpg files by using the `streamFile` member function of the `ESP8266WebServer` class in the URI's request handler. (The same for `WebServer` class of ESP32 arduino core)

You can refer to the code below. It is a component of `FSBrowser.ino`, which is an example of the ESP8266WebServer class.
https://github.com/esp8266/Arduino/blob/1cc6960a5516afb8b244e87574a57986101247bb/libraries/ESP8266WebServer/examples/FSBrowser/FSBrowser.ino#L260-L278

**Comment by medic00** [comment]
Please make demo for add png and css style files.

**Comment by Hieromon** [comment]
You are misunderstanding. I said PageBuilder doesn't support image context replies. If you want to know the program structure of a server-side sketch that can return an image context, catch up on `FSBrowser.ino`.
