### ISSUE TITLE
DynamicPage.ino gives an exception when running on esp8266. 

### ISSUE THREAD

**Issue by JesseRiemens** [Hieromon/PageBuilder#36]
When running the DynamicPage example on an esp8266 it gives an exception when trying to access the / (root) URL.

**Comment by Hieromon** [comment]
@JesseRiemens Thank you for letting me know about this issue.
It's not keeping up with the improvements in the String class of esp8266 arduino core.
Fixed.

**Comment by JesseRiemens** [comment]
Perfect, this works. Can you make a new release so it shows up in PIO?

**Comment by Hieromon** [comment]
@JesseRiemens Released a commit for a fix as v1.5.2. After a while, the PIO and Arduino library managers will crawl and pick a release.
Close an issue.
