### ISSUE TITLE
Consider Using ArduBadge

### ISSUE THREAD

**Issue by gilmaimon** [Hieromon/PageBuilder#6]
Hi :)
Consider using [ArduBadge](https://www.ardu-badge.com/) as an addition to the installing section :)
For PageBuilder it will look like this:
[![arduino-library-badge](https://www.ardu-badge.com/badge/PageBuilder.svg)](https://www.ardu-badge.com/PageBuilder)
Markdown:
`[![arduino-library-badge](https://www.ardu-badge.com/badge/PageBuilder.svg)](https://www.ardu-badge.com/PageBuilder)`

Notice how the badge shows green (signaling that the library is on the Library Manager) and it also points out the latest version. Clicking on the badge opens up a custom installation page and even a link to a ZIP file of the latest version (with explanation on how to install that zip file).

Hope you liked it =)

**Comment by Hieromon** [comment]
I accepted your proposal and updated readme.md with ArduBadge. Thank you.

**Comment by gilmaimon** [comment]
Thank You!
